[gcp]
project_id = "playground-459711"
location = "us-central1" # e.g., "us-central1"
staging_bucket_name = "chatanalyst_bucket"
GOOGLE_API_KEY = "AIzaSyDn1scqc3TP5AxCATg7zySKh57T6Toaf1s"
GOOGLE_GENAI_USE_VERTEXAI = 1

[agent]
resource_id = "projects/playground-459711/locations/us-central1/reasoningEngines/7610458847651561472" 